### ISSUE TITLE
crossplane beta validate fails to see schema for `kind=Robot`

### ISSUE THREAD

**Issue by kaessert** [upbound/provider-upbound#21]
### What happened?

I'm running `beta validate` on 
```
apiVersion: iam.upbound.io/v1alpha1
kind: Robot
metadata:
  name: foobar
---

apiVersion: iam.upbound.io/v1alpha1
kind: Token
metadata:
  name: up-sd666-eks-test-euw2-shd-robot
spec:
  forProvider:
    name: foo
    owner:
      id: bar
      type: users
```

with `xp beta validate apis/crossplane.yaml robot.yaml`

My `crossplane.yaml` contains `[xpkg.upbound.io/upbound/provider-upbound:v0.8.0](http://xpkg.upbound.io/upbound/provider-upbound:v0.8.0)`

It downloaded the schema but is unable to find `kind: Robot`

```
$> xp beta validate apis/crossplane.yaml robot.yaml
[!] could not find CRD/XRD for: iam.upbound.io/v1alpha1, Kind=Robot
[✓] iam.upbound.io/v1alpha1, Kind=Token, up-sd666-eks-test-euw2-shd-robot validated successfully
Total 2 resources: 1 missing schemas, 1 success cases, 0 failure cases
```

As schemas for other resources work just fine, my guess is it's a problem with the upbound-provider.

### How can we reproduce it?

Run steps described earlier

### What environment did it happen in?
Provider Upbound version: `[v0.8.0](http://xpkg.upbound.io/upbound/provider-upbound:v0.8.0)`
